
# 
#  This Source Code Form is subject to the terms of the Mozilla Public License, v.
#  2.0 with a Healthcare Disclaimer.
#  A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
#  be found under the top level directory, named LICENSE.
#  If a copy of the MPL was not distributed with this file, You can obtain one at
#  http://mozilla.org/MPL/2.0/.
#  If a copy of the Healthcare Disclaimer was not distributed with this file, You
#  can obtain one at the project website https://github.com/igia.
# 
#  Copyright (C) 2021-2022 Persistent Systems, Inc.
# 


version: '3.2'

services:
    i2b2-wildfly:
        image: i2b2/i2b2-wildfly:release-v1.7.10.0001
        container_name: i2b2-wildfly
        ports:
          - "${I2B2_WILDFLY_PORT:-8080}:8080"
          - "${I2B2_WILDFLY_MANAGEMENT_PORT:-9990}:9990"
        networks:
          - i2b2net

    i2b2-web:
        image: i2b2/i2b2-web:p1
        container_name: i2b2-web
        command: /run-httpd.sh localhost        
        ports:
          - "${I2B2_WEB_PORT:-80}:80"
          - "${I2B2_WEB_HTTPS_PORT:-443}:443"
        depends_on:
          - i2b2-wildfly
        networks:
          - i2b2net
        
networks:
    i2b2net:
       driver: bridge
